name: Deploy Musiker15 Docs

on:
  push:
    branches:
      - main

# SECURITY: GITHUB_TOKEN auf Minimum beschränken
permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 📦 Install Dependencies
        run: yarn install --frozen-lockfile

      - name: 🏗️ Build Project
        run: yarn build

      - name: 🚀 Upload Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.FTP_PORT }}
          source: "build/*"
          target: "/var/www/html/"
          strip_components: 1

      - name: 🔧 Set File Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.FTP_PORT }}
          script: |
            chown -R www-data:www-data /var/www/html/
